name: Trace PyTorch Model

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch

      - name: JIT trace model
        run: |
          python trace_model.py

      - name: Upload traced model as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: traced-model
          path: traced_model.pt
